# Generated by Django 3.2.9 on 2021-12-03 02:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mailing_address', models.CharField(max_length=255)),
                ('city_state_zip', models.CharField(max_length=255)),
                ('full_mailing_address', models.CharField(max_length=255)),
                ('number_properties_owned', models.IntegerField()),
                ('list_properties_owned', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('street_address', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_mailing_address', models.CharField(max_length=255)),
                ('city_state_zip', models.CharField(max_length=255)),
                ('property_full_address', models.CharField(max_length=255)),
                ('owner_full_mailing_address', models.CharField(max_length=255)),
                ('units_at_property', models.IntegerField()),
                ('g_code', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('number_associated_properties', models.IntegerField()),
                ('list_associated_properties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
    ]
