# Generated by Django 3.2.9 on 2021-12-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0003_alter_property_list_associated_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='list_associated_properties',
        ),
    ]
